# Generated by Django 5.0.6 on 2024-05-31 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.user')),
            ],
        ),
    ]
